-- 코드를 입력하세요
SELECT CC.CAR_ID, CC.CAR_TYPE, CAST(CC.DAILY_FEE*30*(1-CP.DISCOUNT_RATE*0.01)AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP ON CC.CAR_TYPE = CP.CAR_TYPE
WHERE CC.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    WHERE CH.START_DATE <= '2022-11-30' AND CH.END_DATE >= '2022-11-01')
    AND CP.DURATION_TYPE = '30일 이상'
    AND CC.CAR_TYPE IN ('SUV', '세단')
    AND CC.DAILY_FEE*30*(1-CP.DISCOUNT_RATE*0.01)>=500000 
AND CC.DAILY_FEE*30*(1-CP.DISCOUNT_RATE*0.01)<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
    
    